### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by Margen67**

### CODE REVIEW

**Comment by YaLTeR** [comment]
Why get rid of all blank lines tho?

**Comment by Margen67** [comment]
> 
> 
> Why get rid of all blank lines tho?

It's a style thing. I mostly use them to separate jobs.

**Comment by YaLTeR** [comment]
I'd prefer that blank lines are left as is in this case, could you please do that?

**Comment by YaLTeR** [comment]
Ty

**Pull request merged**
